spec-version: 0.36.0
name: scripts
version: 0.1.0

ghc-options: -Wall

dependencies:
- base
- mtl
- turtle
- filepath
- async
- ansi-terminal
- optparse-applicative
- bytestring
- text

library:
  source-dirs: src
  exposed-modules:
    - Scripts
    
