snapshot: lts-21.24
compiler: ghc-9.4.8
compiler-check: match-exact
notify-if-nix-on-path: false
extra-deps:
# included in stackage snapshots as of lts-22.23
- ansi-terminal-1.0
- ansi-terminal-types-0.11.5
